// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApprovalRequest = { id: string, session_id: string, tool_name: string, description: string, created_at: bigint, };
