// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ── config/update ──
 */
export type ConfigUpdateParams = { model_provider: string | null, model: string | null, temperature: number | null, api_key: string | null, base_url: string | null, enable_bash: boolean | null, };
