// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ── config/model/verify ──
 */
export type ConfigModelVerifyParams = { provider: string, model: string, };
