// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigGetResponse = { model_provider: string, model: string, temperature: number, mode: string, autonomy_level: string, working_directory: string, git_branch: string | null, };
