// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { ProtocolVersion } from "./ProtocolVersion";

/**
 * Error frame — any direction.
 */
export type ErrorFrame = { 
/**
 * Protocol version
 */
v: ProtocolVersion, 
/**
 * Correlates to the request id (if applicable)
 */
id: string | null, 
/**
 * Source participant id
 */
src: string, 
/**
 * Destination participant id
 */
dst: string, 
/**
 * Numeric error code
 */
code: number, 
/**
 * Human-readable error message
 */
message: string, 
/**
 * Optional machine-readable error data
 */
data: JsonValue | null, };
