// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * All v1 event types. Names use `<noun>/<past-tense>` convention.
 */
export type Event = "message/started" | "message/chunked" | "message/completed" | "thinking/chunked" | "tool/started" | "tool/completed" | "subagent/spawned" | "subagent/completed" | "nested/tool/started" | "nested/tool/completed" | "status/updated" | "progress/updated" | "approval/required" | "ask/required" | "plan/required" | "session/activity" | "mcp/server/connected" | "error/raised";
