// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ── fs/list-workspace ──
 */
export type FsListWorkspaceParams = { query: string | null, max_results: number | null, };
