// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FsVerifyPathResponse = { exists: boolean, is_file: boolean, is_dir: boolean, canonical_path: string | null, };
