// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpServerDetail = { name: string, command: string, args: Array<string>, envs: { [key in string]?: string }, status: string, tools_count: number, };
