// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ── mcp/server/connect ──
 */
export type McpServerConnectParams = { name: string, };
