// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpServerInfo = { name: string, command: string, status: string, tools_count: number, };
