// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ── mcp/server/create ──
 */
export type McpServerCreateParams = { name: string, command: string, args: Array<string> | null, envs: { [key in string]?: string } | null, };
