// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerDetail } from "./McpServerDetail";

export type McpServerGetResponse = { server: McpServerDetail, };
