// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ── mcp/server/update ──
 */
export type McpServerUpdateParams = { name: string, command: string | null, args: Array<string> | null, envs: { [key in string]?: string } | null, };
