// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * All v1 RPC methods. Names use `<domain>/<verb>` convention.
 */
export type Method = "session/list" | "session/start" | "session/resume" | "session/delete" | "session/turns" | "turn/start" | "turn/interrupt" | "turn/steer" | "tool/list" | "tool/search" | "tool/approve" | "approval/list" | "approval/respond" | "mcp/server/list" | "mcp/server/get" | "mcp/server/create" | "mcp/server/update" | "mcp/server/delete" | "mcp/server/connect" | "mcp/server/disconnect" | "skill/list" | "skill/pin" | "config/get" | "config/update" | "config/mode/set" | "config/autonomy/set" | "config/model/verify" | "fs/browse" | "fs/verify-path" | "fs/list-workspace" | "workspace/list" | "workspace/get";
