// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtocolVersion } from "./ProtocolVersion";

/**
 * Negotiated protocol version after client-server handshake.
 */
export type NegotiatedVersion = { 
/**
 * The version the client requested
 */
requested: ProtocolVersion, 
/**
 * The version the server selected (highest compatible)
 */
selected: ProtocolVersion, 
/**
 * Minimum version the server supports
 */
min_supported: ProtocolVersion, 
/**
 * Maximum version the server supports
 */
max_supported: ProtocolVersion, };
