// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";
import type { ProtocolVersion } from "./ProtocolVersion";

/**
 * Server → Client notification (no request id, no ack expected).
 */
export type NotificationFrame<P> = { 
/**
 * Protocol version
 */
v: ProtocolVersion, 
/**
 * Monotonic sequence number (for frontend gap detection)
 */
seq: bigint, 
/**
 * Source participant id (server)
 */
src: string, 
/**
 * Event name (e.g. "message/chunked")
 */
event: Event, 
/**
 * Event payload
 */
data: P, };
