// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a protocol version for wire serialization.
 */
export type ProtocolVersion = { major: number, minor: number, patch: number, };
