// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Detailed error data that may accompany an ErrorFrame.
 */
export type ProtocolErrorData = { code: number, message: string, details: JsonValue | null, };
