// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Method } from "./Method";
import type { ProtocolVersion } from "./ProtocolVersion";

/**
 * Client → Server request frame.
 */
export type RequestFrame<P> = { 
/**
 * Protocol version
 */
v: ProtocolVersion, 
/**
 * Unique request id (UUID v7, time-ordered)
 */
id: string, 
/**
 * Source participant id
 */
src: string, 
/**
 * Destination participant id (empty for server)
 */
dst: string, 
/**
 * RPC method name (e.g. "session/start")
 */
method: Method, 
/**
 * Method parameters
 */
params: P, };
