// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtocolVersion } from "./ProtocolVersion";

/**
 * Server → Client response frame.
 */
export type ResponseFrame<P> = { 
/**
 * Protocol version
 */
v: ProtocolVersion, 
/**
 * Correlates to the request id
 */
id: string, 
/**
 * Source participant id (server)
 */
src: string, 
/**
 * Destination participant id (original request src)
 */
dst: string, 
/**
 * Response payload
 */
result: P, };
