// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionSummary = { id: string, title: string | null, created_at: bigint, updated_at: bigint, message_count: number, mode: string, };
