// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ── session/start ──
 */
export type SessionStartParams = { title: string | null, model: string | null, mode: string | null, workspace: string | null, };
