// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ── session/list ──
 */
export type SessionListParams = { max_count: number | null, include_archived: boolean | null, };
