// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ── session/delete ──
 */
export type SessionDeleteParams = { session_id: string, };
