// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ── session/turns ──
 */
export type SessionTurnsParams = { session_id: string, max_count: number | null, };
