// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ── tool/list ──
 */
export type ToolListParams = { include_deferred: boolean | null, };
