// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ── turn/interrupt ──
 */
export type TurnInterruptParams = { session_id: string, };
