// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ── turn/steer ──
 */
export type TurnSteerParams = { session_id: string, message: string, };
