// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnSummary = { id: string, user_message: string, started_at: bigint, completed_at: bigint | null, tool_calls: number, status: string, };
