// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentInput } from "./AttachmentInput";

/**
 * ── turn/start ──
 */
export type TurnStartParams = { session_id: string, message: string, attachments: Array<AttachmentInput> | null, };
