// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stub marker — v2 is not yet defined.
 */
export type V2Placeholder = { message: string, };
